

services:
  backend:
    build: ./backend
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload
    ports:
      - "8002:8000"
    volumes:
      - ./backend:/app
    environment:
      - BACKEND_URL=http://backend:8000
    restart: unless-stopped

  frontend:
    build: ./frontend
    command: uvicorn main:app --host 0.0.0.0 --port 8001 --reload
    ports:
      - "8001:8001"
    environment:
      - BACKEND_URL=http://backend:8000
    depends_on:
      - backend
    volumes:
      - ./frontend:/app